# Generated by Django 5.1.4 on 2025-09-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_angilal_cat_img_angilal_description_angilal_slug_and_more'),
    ]

    operations = [
    ]
