# Generated by Django 5.1.7 on 2025-09-04 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angilal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='baraa',
            name='angilal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store_app.angilal'),
        ),
    ]
